idf_component_register(
    SRCS
        "src/display_color.c"
        "src/display_dirty.c"
        "src/display_core.c"
        "src/display_raster.c"
        "src/display_bitmap.c"
        "src/display_text.c"
        "src/lua_module_display.c"
    INCLUDE_DIRS
        "src"
    REQUIRES
        cap_lua
        display_service
        esp_timer
        esp_painter
        lua_module_image
)
